### ISSUE TITLE
Reply

### ISSUE THREAD

**Issue by TechLifeWeb** [pfefferle/wordpress-indieweb-press-this#2]
This may be a WordPress issue, not sure. The bookmarklet for Reply has an issue (at least in Chrome). When you click Reply, if your Press This was previously left in Text mode, where you see markup, you'll see it say the proper syntax  class='u-in-reply-to' 
If you then click the Visual tab, so you can see what your post looks like, all of your reply-to markup and the link goes away.
The Bookmarks for RSVP, Repost and Like seem to work fine. It appears to be the fact that this is a "hidden" link. If, before switching to visual, you put a bit of text in like you are creating a viable link it works.
Also doesn't work at all if your Press This was left in the Visual tab last time. The link doesn't get created at all.

**Comment by snarfed** [comment]
afaik this was fixed by the 4.0 upgrade.
