### ISSUE TITLE
Update to new WordPress version

### ISSUE THREAD

**Issue by pfefferle** [pfefferle/wordpress-indieweb-press-this#4]
see: https://wordpress.org/news/2015/03/wordpress-4-2-beta-1/

**Comment by snarfed** [comment]
thanks for filing this! i put this on my own todo list when i saw that blog post, but i'm a late adopter, so i haven't tried the beta. :P i think @dshanske mentioned you've tried it? what do you think?

**Comment by pfefferle** [comment]
It doesn't seem to work properly :(

WordPress included a version number as GET param I am not sure if this is the only change... I have tested it with my OExchange plugin and this seem to work... Perhaps we only have to run some tests and add simply the version number to skip the warning...

![bildschirmfoto 2015-03-18 um 17 59 22](https://cloud.githubusercontent.com/assets/2373/6714431/8b7f2920-cd98-11e4-8a6f-9804c8565110.png)

**Comment by snarfed** [comment]
done in 164e26c1b4df1aa1370e2afec43b93df9919562e!
